#!/bin/bash

systemctl stop gstudio
systemctl stop nginx
systemctl stop rabbitmq-server
systemctl stop postgresql

killall -u docker

usermod -u 499 docker
groupmod -g 499 docker

find /home/docker -group 1111 -exec chgrp -h docker {} \;
chown -R -h docker /home/docker; 

echo "Reboot of MSS needed to complete the fix. Ensure all client systems are off before rebooting."
echo "`date`: gstudiouser fix applied" >> /var/log/fixlog
