#!/bin/bash
tarball=fixhttps.tar
serverip=repo.myscoolserver.com
wget http://$serverip/fixes/$tarball
tar --keep-directory-symlink --no-overwrite-dir xf $tarball -C / && rm $tarball
systemctl restart nginx
echo "`date`: $tarball applied" >> /var/log/fixlog
