#!/bin/bash
tarball=msshome-brand.tar.xz
serverip=repo.myscoolserver.com
TMPDIR=$(mktemp -d)
cd "$TMPDIR"
wget http://$serverip/fixes/$tarball
tar xf $tarball && rm $tarball
chown root.root * -R
rsync -a ./ /
cd .. && rm -rf "$TMPDIR"
update-alternatives --remove-all default.plymouth
if grep -q 18.04 /etc/os-release; then
    update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/mss-logo/mss-logo.plymouth 150
else
    update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/mss-spinner/mss-spinner.plymouth 150
fi
glib-compile-schemas /usr/share/glib-2.0/schemas/
update-initramfs -u
if [ $(arch) != x86_64 ]; then
    if ! grep -q plymouth /boot/firmware/cmdline.txt; then
        sed -i -e 's@$@ quiet splash plymouth.ignore-serial-consoles@' /boot/firmware/cmdline.txt
    fi
fi
