#!/bin/bash

cat >/usr/local/bin/massuserdel <<EOT
#!/bin/bash

need_help() {
    cat <<EOF

Run as:
sudo $0 <filename>

filename - a file containing the ids of user accounts to be deleted, space separated or one per line

Example:
sudo $0 listofusers.txt

EOF
}

are_you_sure ()  {
        echo  -n "$1 [$2/$3]? "
        while true; do
                read answer
                case $answer in
                        y | Y | yes | YES ) answer="y"; break;;
                        n | N | no | NO ) exit;;
                        *) echo "Please answer (y)es or (n)o.";;
                esac
        done
}

delete_users () {
    filename="$1"
    if [ ! -z "$filename" -a -f "$filename" ]; then
        echo "WARNING: This will delete all the users and their home directories given in the '$filename' file"
        are_you_sure "Are you sure ?" "y" "n"
        echo "Deleting users given in the '$filename' file"
        for user in $(cat $filename); do userdel -r $user; done
    else
        need_help
        exit 0
    fi
}

delete_users $1

EOT
