#!/bin/bash

sed -i "s@GRUB_CMDLINE_LINUX=\"\"@GRUB_CMDLINE_LINUX=\"ipv6.disable=1\"@" /etc/default/grub 
update-grub

apt -y remove xrdp
apt update

su - mssadmin <<EOF
mkdir xrdp && cd xrdp
wget https://www.c-nergy.be/downloads/xRDP/xrdp-installer-1.3.zip && unzip xrdp-installer-1.3.zip && chmod +x xrdp-installer-1.3.sh 
./xrdp-installer-1.3.sh -c -l -s
EOF

rm -rf /home/mssadmin/Downloads/xrdp
rm -rf /home/mssadmin/Downloads/xorgxrdp
rm -rf /home/mssadmin/Downloads/griffon*.bmp
rm -rf /home/mssadmin/xrdp

serverip=repo.myscoolserver.com
wget http://$serverip/fixes/mss-xrdp.tar
tar xf mss-xrdp.tar -C / && rm mss-xrdp.tar
chown root.root /usr/local/share/xrdp/mss_logo_xrdp.bmp
chmod 644 /usr/local/share/xrdp/mss_logo_xrdp.bmp

sed -i "s/^bind.*/bind 127.0.0.1/g" /etc/redis/redis.conf

echo "`date`: IPv6 disabled and xrdp updated successfully" >> /var/log/fixlog && \
echo "`date`: IPv6 disabled and xrdp updated successfully. A reboot shall be required to effect this change."
