#!/bin/bash

targetfile=/lib/systemd/system/kolibri-server.service
cat > entry <<- EOF
TimeoutStartSec=infinity
EOF
replacement=$(sed 's@[/\&]@\\&@g;s/$/\\/' entry; echo .)
replacement=${replacement%.}
if ! grep -q "^TimeoutStartSec=infinity" "$targetfile"; then
  sed -i -e "/KillMode/a$replacement" $targetfile
fi
