#!/bin/bash

sed -i "s@GRUB_CMDLINE_LINUX=\"\"@GRUB_CMDLINE_LINUX=\"ipv6.disable=1\"@" /etc/default/grub 
update-grub

apt -y remove xrdp

su -u mssadmin bash <<EOF
wget https://www.c-nergy.be/downloads/xRDP/xrdp-installer-1.3.zip && unzip xrdp-installer-1.3.zip && chmod +x xrdp-installer-1.3.sh 
./xrdp-installer-1.3.sh -c -l -s
EOF

wget http://$serverip/fixes/mss-xrdp.tar
tar xf mss-xrdp.tar -C / && rm mss-xrdp.tar
chown root.root /usr/local/share/xrdp/mss_logo_xrdp.bmp
chmod 644 /usr/local/share/xrdp/mss_logo_xrdp.bmp

echo "`date`: IPv6 disabled and xrdp updated successfully" >> /var/log/fixlog && echo "`date`: IPv6 disabled and xrdp updated successfully. A reboot shall be required to effect this change."
