#!/bin/bash

[ ! -d /home/installer ] && mkdir -p /home/installer
[ ! -d /installer ] && mkdir -p /installer
! grep -q "/home/installer" /etc/fstab && echo "/home/installer	/installer	none	defaults,bind	0 0" >> /etc/fstab
mount /installer

# For mounting /installer onto install target client and getting latest mssinstaller.bsx to it
ltsConf_file=/etc/ltsp/ltsp.conf
cat > entry <<- EOF
# For getting latest mssinstaller.bsx to install target client
FSTAB_99="server:/installer /installer nfs defaults,nolock,rsize=32768,wsize=32768 0 0"'
EOF
replacement=$(sed 's@[/\&]@\\&@g;s/$/\\/' entry; echo .)
replacement=${replacement%.}
if ! grep -q "^FSTAB_99" "$ltsConf_file"; then
  sed -i -e "/FSTAB_02/a$replacement" $ltsConf_file
fi

echo "/installer   *(ro,root_squash,async,no_subtree_check)" > /etc/exports.d/ltsp-mss-installer.exports
exportfs -r

cat >/var/www/html/mss/syncwebcontent <<EOT
#!/bin/bash
rsync -avP --exclude 'mongo.log.*' --exclude 'postmsssetup' --exclude 'syncwebcontent' rsync://\$serverip:/mssweb/ /var/www/html/mss/
echo "Web content sync completed."
EOT

# postmsssetup
cat >/var/www/html/mss/postmsssetup <<EOT
#!/bin/bash
mssupdate \$serverip syncwebcontent
EOT

# setup rsync daemon for speed
cat >/etc/rsyncd.conf <<EOT
gid = users
read only = true
use chroot = true
transfer logging = true
log format = %h %o %f %l %b
log file = /var/log/rsyncd.log
pid file = /var/run/rsyncd.pid
#hosts allow = trusted.hosts
slp refresh = 300
use slp = false
#[Example]
#       path = /home/Example
#       comment = An Example
#       auth users = user
#       secrets file = /etc/rsyncd.secrets
[mssweb]
        path = /var/www/html/mss
        comment = MSS Web Content
EOT

echo "`date`: activated mss installer" >> /var/log/fixlog
