#!/bin/bash

## zsync needed to sync updates to installer files
apt install -y zsync

# create installer's abode
[ ! -d /home/installer ] && mkdir -p /home/installer
[ ! -d /installer ] && mkdir -p /installer
! grep -q "/home/installer" /etc/fstab && echo "/home/installer	/installer	none	defaults,bind	0 0" >> /etc/fstab
mount /installer

## For mounting /installer onto install target client and getting latest mssinstaller.bsx to it
ltsConf_file=/etc/ltsp/ltsp.conf
cat > entry <<- EOF
# For getting latest mssinstaller.bsx to install target client
FSTAB_99="server:/installer /installer nfs defaults,nolock,rsize=32768,wsize=32768 0 0"
EOF
replacement=$(sed 's@[/\&]@\\&@g;s/$/\\/' entry; echo .)
replacement=${replacement%.}
if ! grep -q "^FSTAB_99" "$ltsConf_file"; then
  sed -i -e "/FSTAB_02/a$replacement" $ltsConf_file
fi

echo "/installer   *(ro,root_squash,async,no_subtree_check)" > /etc/exports.d/ltsp-mss-installer.exports
exportfs -r

## for applying post mss setup customisations

cat >/installer/postmsssetup <<EOT
#!/bin/bash
mssupdate \$serverip syncwebcontent
EOT

ln -s /installer/postmsssetup /var/www/html/postmsssetup

cat >/installer/syncwebcontent <<EOT
#!/bin/bash
rsync -avP --exclude 'mongo.log.*' --exclude 'postmsssetup' --exclude 'syncwebcontent' rsync://\$serverip:/mssweb/ /var/www/html/mss/
echo "Web content sync completed."
EOT

ln -s /installer/syncwebcontent /var/www/html/syncwebcontent

# setup rsync daemon for speed
cat >/etc/rsyncd.conf <<EOT
gid = users
read only = true
use chroot = true
transfer logging = true
log format = %h %o %f %l %b
log file = /var/log/rsyncd.log
pid file = /var/run/rsyncd.pid
#hosts allow = trusted.hosts
slp refresh = 300
use slp = false
#[Example]
#       path = /home/Example
#       comment = An Example
#       auth users = user
#       secrets file = /etc/rsyncd.secrets
[mssweb]
        path = /var/www/html/mss
        comment = MSS Web Content
EOT

# fetch latest installer
rsync -avP -e "ssh -p 2230" rsync://support.myscoolserver.com:/home/mss/content2/mssinstaller.bsx /installer/mssinstaller.bsx
chmod a+x /installer/mssinstaller.bsx
# This is needed after a zsync update which leaves it as owner rw only
[ -f /installer/mss.tar ] && chmod a+r /installer/mss.tar 
[ -f /installer/kolibri.tar ] && chmod a+r /installer/kolibri.tar

echo "`date`: activated mss installer" >> /var/log/fixlog
