#!/bin/bash

APP=kolibri
systemctl stop $APP
cd /recovery/offlinewebarchives/
wget https://github.com/learningequality/kolibri/releases/download/v0.12.2/kolibri-0.12.2.pex -O $APP.pex
mv kolibri.pex /usr/local/bin/kolibri
chmod a+x /usr/local/bin/kolibri
rm /recovery/offlinewebarchives/$APP.pex
chown mssadmin /home/mssadmin -R
systemctl enable $APP
systemctl start $APP

echo "`date`: $APP upgrade successful." >> /var/log/fixlog
