#!/bin/bash
serverip=repo.myscoolserver.com
wget http://$serverip/fixes/offliewebinfra.tar.xz
wget http://$serverip/fixes/offliewebinfraskel

tar cvJf offliewebinfra.tar.xz -T offliewebinfraskel
tar xf offliewebinfra.tar.xz -C /

cd /var/www/html/mss/indexer
./indexer.sh

mssipchange

echo "`date`: offlinewebinfra updated" >> /var/log/fixlog

