#!/bin/bash
serverip=recherchetech.github.io
wget http://$serverip/mss/fixes/offlinewebinfra.tar.xz
wget http://$serverip/mss/fixes/offlinewebinfraskel

#safety net
tar cvJf /tmp/offliewebinfra.tar.xz -T offlinewebinfraskel

#roll out update
tar xf offlinewebinfra.tar.xz -C /
mv offlinewebinfra.tar.xz /recovery/offlinewebarchives/

cd /var/www/html/mss/indexer
./indexer.sh

mssipchange

echo "`date`: offlinewebinfra updated" >> /var/log/fixlog
echo "You need to delete /tmp/offliewebinfra.tar.xz manually if all is OK at http://server/"
