#!/bin/bash

apt install -y zsync

cd /installer
( zsync http://support.myscoolserver.com:3080/mss/content2/mss.tar.zsync && \
chmod a+r mss.tar && rm mss.tar.zs-old && \
echo "`date`: mss.tar installer image updated successfully" >> /var/log/fixlog ) || \
echo "`date`: mss.tar installer image update process failed" >> /var/log/fixlog
