#!/bin/bash
#setup dnsmasq on IP address change
if [ "$2" = "up" ];then
	if test -f /var/www/htdocs/ap.conf; then
		. /var/www/htdocs/ap.conf
		if [[ x"$NET_CONNECT == xtrue" ]]; then
			. /usr/bin/networkvariables.sh
			if [ ! -z "$DHCPD_INTERFACE" ]; then
				iptables -t nat -A POSTROUTING -o $DHCPD_INTERFACE -j MASQUERADE
			fi
		fi
	fi
fi

